### PR TITLE
60% of quests translated to ru_ru

### PR DESCRIPTION
**Pull request by drcrazy**

### CODE REVIEW

**Comment by Sunekaer** [comment]
niiice

**Comment by aaronhowser1** [comment]
Please be aware of the [new English file](https://github.com/FTBTeam/FTB-Academy/commit/7672ebe952074675e9cca8b2e3c8046b403fac3a) and its changes.

**Comment by aaronhowser1** [comment]
Why close?

**Comment by drcrazy** [comment]
Yeah

**Pull request closed without merging**
