### PR TITLE
100% of ru_ru translation for quests

### PR DESCRIPTION
**Pull request by drcrazy**

### CODE REVIEW

**Comment by aaronhowser1** [comment]
@drcrazy is this completely ready for a pull?

**Comment by nikitasA1NT** [comment]
@drcrazy I decided to translate the guide into Russian. Cloned the repository to himself, transferred half without images. How to add this to modpack?

**Comment by drcrazy** [comment]
Copy the entire /config/ftbguides/modpack_guide/ folder and rename it, adding the language to the end (so for Russian, it would be /modpack_guide_ru_ru/)

**Comment by aaronhowser1** [comment]
Please be aware of the changes made in https://github.com/FTBTeam/FTB-Academy/commit/8b1c694eea0021acaac07ba79fa143298e6008cf

**Comment by aaronhowser1** [comment]
Thank you *very* much for your contribution!

**Pull request merged**
